package astrobox:main;

// 傻逼vsc会在这报错 别管

use astrobox:psys-host/os;
use astrobox:psys-host/transport;
use astrobox:psys-host/ui;
use astrobox:psys-host/dialog;
use astrobox:psys-host/device;
use astrobox:psys-host/register;
use astrobox:psys-host/event;
use astrobox:psys-host/queue;
use astrobox:psys-host/timer;
use astrobox:psys-host/interconnect;
use astrobox:psys-host/thirdpartyapp;

use astrobox:psys-plugin/lifecycle;
use astrobox:psys-plugin/event as plugin-event;

world psys-world {
  import os;
  import transport;
  import ui;
  import dialog;
  import device;
  import register;
  import event;
  import queue;
  import timer;
  import interconnect;
  import thirdpartyapp;

  export lifecycle;
  export plugin-event;
}
